---
- hosts: "{{ servidores }}"
  become: true
  gather_facts: no
  tasks:
  - name: validamos conexion web
    block:
      - name: comprobamos si la web responde
        uri:
          url: "http://localhost"
    rescue:
      - name: asumo que el servicio esta paradoy se levanta 
        service:
          name: httpd
          state: started
    ignore_errors: true
  - name: mostrar mensaje
    debug:
      msg: "La terea fue bien"
